numbers = [12, 45, 7, 89, 34, 56, 23, 90, 11, 67,20,44,54,65,87,90,55,11,22,80]

print("Numbers:", numbers)
print("Highest:", max(numbers))
print("Lowest:", min(numbers))
print("Average:", sum(numbers) / len(numbers))

